version: '3.7'

services:
  mongo-db:
    container_name: nosql_db
    image: mongo:6.0.2
    ports:
        - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin