version: '3.3'

services:
  postgresql-db:
    container_name: psql-db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: <db_name>
